// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission12.Models;

namespace Mission12.Migrations
{
    [DbContext(typeof(GroupContext))]
    [Migration("20220322215044_AllDays")]
    partial class AllDays
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission12.Models.Appointment", b =>
                {
                    b.Property<long>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1L,
                            Available = true,
                            Time = new DateTime(2022, 3, 27, 8, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 2L,
                            Available = true,
                            Time = new DateTime(2022, 3, 27, 9, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 3L,
                            Available = true,
                            Time = new DateTime(2022, 3, 27, 10, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 4L,
                            Available = true,
                            Time = new DateTime(2022, 3, 27, 11, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 5L,
                            Available = true,
                            Time = new DateTime(2022, 3, 27, 12, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 6L,
                            Available = true,
                            Time = new DateTime(2022, 3, 27, 13, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 7L,
                            Available = true,
                            Time = new DateTime(2022, 3, 27, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 8L,
                            Available = true,
                            Time = new DateTime(2022, 3, 27, 15, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 9L,
                            Available = true,
                            Time = new DateTime(2022, 3, 27, 16, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 10L,
                            Available = true,
                            Time = new DateTime(2022, 3, 27, 17, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 11L,
                            Available = true,
                            Time = new DateTime(2022, 3, 27, 18, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 12L,
                            Available = true,
                            Time = new DateTime(2022, 3, 27, 19, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 13L,
                            Available = true,
                            Time = new DateTime(2022, 3, 27, 20, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 14L,
                            Available = true,
                            Time = new DateTime(2022, 3, 28, 8, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 15L,
                            Available = true,
                            Time = new DateTime(2022, 3, 28, 9, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 16L,
                            Available = true,
                            Time = new DateTime(2022, 3, 28, 10, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 17L,
                            Available = true,
                            Time = new DateTime(2022, 3, 28, 11, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 18L,
                            Available = true,
                            Time = new DateTime(2022, 3, 28, 12, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 19L,
                            Available = true,
                            Time = new DateTime(2022, 3, 28, 13, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 20L,
                            Available = true,
                            Time = new DateTime(2022, 3, 28, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 21L,
                            Available = true,
                            Time = new DateTime(2022, 3, 28, 15, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 22L,
                            Available = true,
                            Time = new DateTime(2022, 3, 28, 16, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 23L,
                            Available = true,
                            Time = new DateTime(2022, 3, 28, 17, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 24L,
                            Available = true,
                            Time = new DateTime(2022, 3, 28, 18, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 25L,
                            Available = true,
                            Time = new DateTime(2022, 3, 28, 19, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 26L,
                            Available = true,
                            Time = new DateTime(2022, 3, 28, 20, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 27L,
                            Available = true,
                            Time = new DateTime(2022, 3, 29, 8, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 28L,
                            Available = true,
                            Time = new DateTime(2022, 3, 29, 9, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 29L,
                            Available = true,
                            Time = new DateTime(2022, 3, 29, 10, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 30L,
                            Available = true,
                            Time = new DateTime(2022, 3, 29, 11, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 31L,
                            Available = true,
                            Time = new DateTime(2022, 3, 29, 12, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 32L,
                            Available = true,
                            Time = new DateTime(2022, 3, 29, 13, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 33L,
                            Available = true,
                            Time = new DateTime(2022, 3, 29, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 34L,
                            Available = true,
                            Time = new DateTime(2022, 3, 29, 15, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 35L,
                            Available = true,
                            Time = new DateTime(2022, 3, 29, 16, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 36L,
                            Available = true,
                            Time = new DateTime(2022, 3, 29, 17, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 37L,
                            Available = true,
                            Time = new DateTime(2022, 3, 29, 18, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 38L,
                            Available = true,
                            Time = new DateTime(2022, 3, 29, 19, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 39L,
                            Available = true,
                            Time = new DateTime(2022, 3, 29, 20, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 40L,
                            Available = true,
                            Time = new DateTime(2022, 3, 30, 8, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 41L,
                            Available = true,
                            Time = new DateTime(2022, 3, 30, 9, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 42L,
                            Available = true,
                            Time = new DateTime(2022, 3, 30, 10, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 43L,
                            Available = true,
                            Time = new DateTime(2022, 3, 30, 11, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 44L,
                            Available = true,
                            Time = new DateTime(2022, 3, 30, 12, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 45L,
                            Available = true,
                            Time = new DateTime(2022, 3, 30, 13, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 46L,
                            Available = true,
                            Time = new DateTime(2022, 3, 30, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 47L,
                            Available = true,
                            Time = new DateTime(2022, 3, 30, 15, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 48L,
                            Available = true,
                            Time = new DateTime(2022, 3, 30, 16, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 49L,
                            Available = true,
                            Time = new DateTime(2022, 3, 30, 17, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 50L,
                            Available = true,
                            Time = new DateTime(2022, 3, 30, 18, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 51L,
                            Available = true,
                            Time = new DateTime(2022, 3, 30, 19, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 52L,
                            Available = true,
                            Time = new DateTime(2022, 3, 30, 20, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 53L,
                            Available = true,
                            Time = new DateTime(2022, 3, 31, 8, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 54L,
                            Available = true,
                            Time = new DateTime(2022, 3, 31, 9, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 55L,
                            Available = true,
                            Time = new DateTime(2022, 3, 31, 10, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 56L,
                            Available = true,
                            Time = new DateTime(2022, 3, 31, 11, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 57L,
                            Available = true,
                            Time = new DateTime(2022, 3, 31, 12, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 58L,
                            Available = true,
                            Time = new DateTime(2022, 3, 31, 13, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 59L,
                            Available = true,
                            Time = new DateTime(2022, 3, 31, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 60L,
                            Available = true,
                            Time = new DateTime(2022, 3, 31, 15, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 61L,
                            Available = true,
                            Time = new DateTime(2022, 3, 31, 16, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 62L,
                            Available = true,
                            Time = new DateTime(2022, 3, 31, 17, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 63L,
                            Available = true,
                            Time = new DateTime(2022, 3, 31, 18, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 64L,
                            Available = true,
                            Time = new DateTime(2022, 3, 31, 19, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 65L,
                            Available = true,
                            Time = new DateTime(2022, 3, 31, 20, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 66L,
                            Available = true,
                            Time = new DateTime(2022, 4, 1, 8, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 67L,
                            Available = true,
                            Time = new DateTime(2022, 4, 1, 9, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 68L,
                            Available = true,
                            Time = new DateTime(2022, 4, 1, 10, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 69L,
                            Available = true,
                            Time = new DateTime(2022, 4, 1, 11, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 70L,
                            Available = true,
                            Time = new DateTime(2022, 4, 1, 12, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 71L,
                            Available = true,
                            Time = new DateTime(2022, 4, 1, 13, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 72L,
                            Available = true,
                            Time = new DateTime(2022, 4, 1, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 73L,
                            Available = true,
                            Time = new DateTime(2022, 4, 1, 15, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 74L,
                            Available = true,
                            Time = new DateTime(2022, 4, 1, 16, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 75L,
                            Available = true,
                            Time = new DateTime(2022, 4, 1, 17, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 76L,
                            Available = true,
                            Time = new DateTime(2022, 4, 1, 18, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 77L,
                            Available = true,
                            Time = new DateTime(2022, 4, 1, 19, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 78L,
                            Available = true,
                            Time = new DateTime(2022, 4, 1, 20, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 79L,
                            Available = true,
                            Time = new DateTime(2022, 4, 2, 8, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 80L,
                            Available = true,
                            Time = new DateTime(2022, 4, 2, 9, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 81L,
                            Available = true,
                            Time = new DateTime(2022, 4, 2, 10, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 82L,
                            Available = true,
                            Time = new DateTime(2022, 4, 2, 11, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 83L,
                            Available = true,
                            Time = new DateTime(2022, 4, 2, 12, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 84L,
                            Available = true,
                            Time = new DateTime(2022, 4, 2, 13, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 85L,
                            Available = true,
                            Time = new DateTime(2022, 4, 2, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 86L,
                            Available = true,
                            Time = new DateTime(2022, 4, 2, 15, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 87L,
                            Available = true,
                            Time = new DateTime(2022, 4, 2, 16, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 88L,
                            Available = true,
                            Time = new DateTime(2022, 4, 2, 17, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 89L,
                            Available = true,
                            Time = new DateTime(2022, 4, 2, 18, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 90L,
                            Available = true,
                            Time = new DateTime(2022, 4, 2, 19, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            AppointmentId = 91L,
                            Available = true,
                            Time = new DateTime(2022, 4, 2, 20, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("Mission12.Models.Group", b =>
                {
                    b.Property<long>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AppointmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1L,
                            AppointmentId = 1L,
                            Email = "thomas@thomas.com",
                            Name = "thomas",
                            Phone = "9999999",
                            Size = 12
                        });
                });

            modelBuilder.Entity("Mission12.Models.Group", b =>
                {
                    b.HasOne("Mission12.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
